export const urls = {
  login: '/login',
  logout: '/logout',
  userDashboard: (id: number) => `/user/${id}/dashboard`,
  userBills: (id: number) => `/user/${id}/bills`,
  userBillDetails: (id: number) => `/user/bill/${id}`,
  employeeBills: '/admin/employee/bills',
  adminCategoryWiseBills: (userId: number) => `/admin/categoryWiseBills/${userId}`,
  adminCategoryBills: (userId: number, categoryId: number) =>
    `/admin/categoryWiseBills/${userId}/${categoryId}`,
  adminVerifyBill: (billId: number) => `/admin/bills/${billId}/verify`,
  adminRejectBill: (billId: number) => `/admin/bills/${billId}/verify`,
  adminBulkReimburse: (batchId: number) => `/admin/bills/${batchId}/bulk-reimburse`,
  adminUserBulkReimburse: '/admin/bills/bulk-reimburse',
  adminReimburseByPivot: '/admin/bills/reimburse-by-pivot',
  categories: '/categories',
  categoryCreate: '/categories',
  categoryUpdate: (id: number) => `/categories/${id}`,
  categoryDelete: (id: number) => `/categories/${id}`,
  bills: '/bills',
  batchPreview: (id: number) => `/batches/${id}/preview`,
  batchSubmit: (id: number) => `/batches/${id}/submit`,
}
